// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: command.proto

package org.bwapi.proxy.messages;

public final class Commands {
  private Commands() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  /**
   * Protobuf enum {@code messages.CommandType}
   */
  public enum CommandType
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>none = 1;</code>
     */
    none(0, 1),
    /**
     * <code>attackMove = 2;</code>
     */
    attackMove(1, 2),
    /**
     * <code>attackUnit = 3;</code>
     */
    attackUnit(2, 3),
    /**
     * <code>rightClick = 4;</code>
     */
    rightClick(3, 4),
    /**
     * <code>rightClickUnit = 5;</code>
     */
    rightClickUnit(4, 5),
    /**
     * <code>train = 6;</code>
     */
    train(5, 6),
    /**
     * <code>build = 7;</code>
     */
    build(6, 7),
    /**
     * <code>buildAddon = 8;</code>
     */
    buildAddon(7, 8),
    /**
     * <code>research = 9;</code>
     */
    research(8, 9),
    /**
     * <code>upgrade = 10;</code>
     */
    upgrade(9, 10),
    /**
     * <code>stop = 11;</code>
     */
    stop(10, 11),
    /**
     * <code>holdPosition = 12;</code>
     */
    holdPosition(11, 12),
    /**
     * <code>patrol = 13;</code>
     */
    patrol(12, 13),
    /**
     * <code>follow = 14;</code>
     */
    follow(13, 14),
    /**
     * <code>setRallyPosition = 15;</code>
     */
    setRallyPosition(14, 15),
    /**
     * <code>setRallyUnit = 16;</code>
     */
    setRallyUnit(15, 16),
    /**
     * <code>repair = 17;</code>
     */
    repair(16, 17),
    /**
     * <code>morph = 18;</code>
     */
    morph(17, 18),
    /**
     * <code>burrow = 19;</code>
     */
    burrow(18, 19),
    /**
     * <code>unburrow = 20;</code>
     */
    unburrow(19, 20),
    /**
     * <code>siege = 21;</code>
     */
    siege(20, 21),
    /**
     * <code>unsiege = 22;</code>
     */
    unsiege(21, 22),
    /**
     * <code>cloak = 23;</code>
     */
    cloak(22, 23),
    /**
     * <code>decloak = 24;</code>
     */
    decloak(23, 24),
    /**
     * <code>lift = 25;</code>
     */
    lift(24, 25),
    /**
     * <code>land = 26;</code>
     */
    land(25, 26),
    /**
     * <code>load = 27;</code>
     */
    load(26, 27),
    /**
     * <code>unload = 28;</code>
     */
    unload(27, 28),
    /**
     * <code>unloadAll = 29;</code>
     */
    unloadAll(28, 29),
    /**
     * <code>unloadAllPosition = 30;</code>
     */
    unloadAllPosition(29, 30),
    /**
     * <code>cancelConstruction = 31;</code>
     */
    cancelConstruction(30, 31),
    /**
     * <code>haltConstruction = 32;</code>
     */
    haltConstruction(31, 32),
    /**
     * <code>cancelMorph = 33;</code>
     */
    cancelMorph(32, 33),
    /**
     * <code>cancelTrain = 34;</code>
     */
    cancelTrain(33, 34),
    /**
     * <code>cancelTrainSlot = 35;</code>
     */
    cancelTrainSlot(34, 35),
    /**
     * <code>cancelAddon = 36;</code>
     */
    cancelAddon(35, 36),
    /**
     * <code>cancelResearch = 37;</code>
     */
    cancelResearch(36, 37),
    /**
     * <code>cancelUpgrade = 38;</code>
     */
    cancelUpgrade(37, 38),
    /**
     * <code>useTech = 39;</code>
     */
    useTech(38, 39),
    /**
     * <code>useTechPosition = 40;</code>
     */
    useTechPosition(39, 40),
    /**
     * <code>useTechTarget = 41;</code>
     */
    useTechTarget(40, 41),
    ;

    /**
     * <code>none = 1;</code>
     */
    public static final int none_VALUE = 1;
    /**
     * <code>attackMove = 2;</code>
     */
    public static final int attackMove_VALUE = 2;
    /**
     * <code>attackUnit = 3;</code>
     */
    public static final int attackUnit_VALUE = 3;
    /**
     * <code>rightClick = 4;</code>
     */
    public static final int rightClick_VALUE = 4;
    /**
     * <code>rightClickUnit = 5;</code>
     */
    public static final int rightClickUnit_VALUE = 5;
    /**
     * <code>train = 6;</code>
     */
    public static final int train_VALUE = 6;
    /**
     * <code>build = 7;</code>
     */
    public static final int build_VALUE = 7;
    /**
     * <code>buildAddon = 8;</code>
     */
    public static final int buildAddon_VALUE = 8;
    /**
     * <code>research = 9;</code>
     */
    public static final int research_VALUE = 9;
    /**
     * <code>upgrade = 10;</code>
     */
    public static final int upgrade_VALUE = 10;
    /**
     * <code>stop = 11;</code>
     */
    public static final int stop_VALUE = 11;
    /**
     * <code>holdPosition = 12;</code>
     */
    public static final int holdPosition_VALUE = 12;
    /**
     * <code>patrol = 13;</code>
     */
    public static final int patrol_VALUE = 13;
    /**
     * <code>follow = 14;</code>
     */
    public static final int follow_VALUE = 14;
    /**
     * <code>setRallyPosition = 15;</code>
     */
    public static final int setRallyPosition_VALUE = 15;
    /**
     * <code>setRallyUnit = 16;</code>
     */
    public static final int setRallyUnit_VALUE = 16;
    /**
     * <code>repair = 17;</code>
     */
    public static final int repair_VALUE = 17;
    /**
     * <code>morph = 18;</code>
     */
    public static final int morph_VALUE = 18;
    /**
     * <code>burrow = 19;</code>
     */
    public static final int burrow_VALUE = 19;
    /**
     * <code>unburrow = 20;</code>
     */
    public static final int unburrow_VALUE = 20;
    /**
     * <code>siege = 21;</code>
     */
    public static final int siege_VALUE = 21;
    /**
     * <code>unsiege = 22;</code>
     */
    public static final int unsiege_VALUE = 22;
    /**
     * <code>cloak = 23;</code>
     */
    public static final int cloak_VALUE = 23;
    /**
     * <code>decloak = 24;</code>
     */
    public static final int decloak_VALUE = 24;
    /**
     * <code>lift = 25;</code>
     */
    public static final int lift_VALUE = 25;
    /**
     * <code>land = 26;</code>
     */
    public static final int land_VALUE = 26;
    /**
     * <code>load = 27;</code>
     */
    public static final int load_VALUE = 27;
    /**
     * <code>unload = 28;</code>
     */
    public static final int unload_VALUE = 28;
    /**
     * <code>unloadAll = 29;</code>
     */
    public static final int unloadAll_VALUE = 29;
    /**
     * <code>unloadAllPosition = 30;</code>
     */
    public static final int unloadAllPosition_VALUE = 30;
    /**
     * <code>cancelConstruction = 31;</code>
     */
    public static final int cancelConstruction_VALUE = 31;
    /**
     * <code>haltConstruction = 32;</code>
     */
    public static final int haltConstruction_VALUE = 32;
    /**
     * <code>cancelMorph = 33;</code>
     */
    public static final int cancelMorph_VALUE = 33;
    /**
     * <code>cancelTrain = 34;</code>
     */
    public static final int cancelTrain_VALUE = 34;
    /**
     * <code>cancelTrainSlot = 35;</code>
     */
    public static final int cancelTrainSlot_VALUE = 35;
    /**
     * <code>cancelAddon = 36;</code>
     */
    public static final int cancelAddon_VALUE = 36;
    /**
     * <code>cancelResearch = 37;</code>
     */
    public static final int cancelResearch_VALUE = 37;
    /**
     * <code>cancelUpgrade = 38;</code>
     */
    public static final int cancelUpgrade_VALUE = 38;
    /**
     * <code>useTech = 39;</code>
     */
    public static final int useTech_VALUE = 39;
    /**
     * <code>useTechPosition = 40;</code>
     */
    public static final int useTechPosition_VALUE = 40;
    /**
     * <code>useTechTarget = 41;</code>
     */
    public static final int useTechTarget_VALUE = 41;


    public final int getNumber() { return value; }

    public static CommandType valueOf(int value) {
      switch (value) {
        case 1: return none;
        case 2: return attackMove;
        case 3: return attackUnit;
        case 4: return rightClick;
        case 5: return rightClickUnit;
        case 6: return train;
        case 7: return build;
        case 8: return buildAddon;
        case 9: return research;
        case 10: return upgrade;
        case 11: return stop;
        case 12: return holdPosition;
        case 13: return patrol;
        case 14: return follow;
        case 15: return setRallyPosition;
        case 16: return setRallyUnit;
        case 17: return repair;
        case 18: return morph;
        case 19: return burrow;
        case 20: return unburrow;
        case 21: return siege;
        case 22: return unsiege;
        case 23: return cloak;
        case 24: return decloak;
        case 25: return lift;
        case 26: return land;
        case 27: return load;
        case 28: return unload;
        case 29: return unloadAll;
        case 30: return unloadAllPosition;
        case 31: return cancelConstruction;
        case 32: return haltConstruction;
        case 33: return cancelMorph;
        case 34: return cancelTrain;
        case 35: return cancelTrainSlot;
        case 36: return cancelAddon;
        case 37: return cancelResearch;
        case 38: return cancelUpgrade;
        case 39: return useTech;
        case 40: return useTechPosition;
        case 41: return useTechTarget;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<CommandType>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static com.google.protobuf.Internal.EnumLiteMap<CommandType>
        internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<CommandType>() {
            public CommandType findValueByNumber(int number) {
              return CommandType.valueOf(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(index);
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return org.bwapi.proxy.messages.Commands.getDescriptor().getEnumTypes().get(0);
    }

    private static final CommandType[] VALUES = values();

    public static CommandType valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      return VALUES[desc.getIndex()];
    }

    private final int index;
    private final int value;

    private CommandType(int index, int value) {
      this.index = index;
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:messages.CommandType)
  }

  public interface CommandOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required .messages.CommandType type = 1;
    /**
     * <code>required .messages.CommandType type = 1;</code>
     */
    boolean hasType();
    /**
     * <code>required .messages.CommandType type = 1;</code>
     */
    org.bwapi.proxy.messages.Commands.CommandType getType();

    // required .messages.UnitId self = 2;
    /**
     * <code>required .messages.UnitId self = 2;</code>
     */
    boolean hasSelf();
    /**
     * <code>required .messages.UnitId self = 2;</code>
     */
    org.bwapi.proxy.messages.GameMessages.UnitId getSelf();
    /**
     * <code>required .messages.UnitId self = 2;</code>
     */
    org.bwapi.proxy.messages.GameMessages.UnitIdOrBuilder getSelfOrBuilder();

    // optional .messages.Position pos = 3;
    /**
     * <code>optional .messages.Position pos = 3;</code>
     */
    boolean hasPos();
    /**
     * <code>optional .messages.Position pos = 3;</code>
     */
    org.bwapi.proxy.messages.BasicTypes.Position getPos();
    /**
     * <code>optional .messages.Position pos = 3;</code>
     */
    org.bwapi.proxy.messages.BasicTypes.PositionOrBuilder getPosOrBuilder();

    // optional .messages.TilePosition tilePos = 4;
    /**
     * <code>optional .messages.TilePosition tilePos = 4;</code>
     */
    boolean hasTilePos();
    /**
     * <code>optional .messages.TilePosition tilePos = 4;</code>
     */
    org.bwapi.proxy.messages.BasicTypes.TilePosition getTilePos();
    /**
     * <code>optional .messages.TilePosition tilePos = 4;</code>
     */
    org.bwapi.proxy.messages.BasicTypes.TilePositionOrBuilder getTilePosOrBuilder();

    // optional .messages.UnitId target = 5;
    /**
     * <code>optional .messages.UnitId target = 5;</code>
     */
    boolean hasTarget();
    /**
     * <code>optional .messages.UnitId target = 5;</code>
     */
    org.bwapi.proxy.messages.GameMessages.UnitId getTarget();
    /**
     * <code>optional .messages.UnitId target = 5;</code>
     */
    org.bwapi.proxy.messages.GameMessages.UnitIdOrBuilder getTargetOrBuilder();

    // optional .messages.UnitType unitType = 6;
    /**
     * <code>optional .messages.UnitType unitType = 6;</code>
     */
    boolean hasUnitType();
    /**
     * <code>optional .messages.UnitType unitType = 6;</code>
     */
    org.bwapi.proxy.messages.GameMessages.UnitType getUnitType();
    /**
     * <code>optional .messages.UnitType unitType = 6;</code>
     */
    org.bwapi.proxy.messages.GameMessages.UnitTypeOrBuilder getUnitTypeOrBuilder();

    // optional .messages.TechType techType = 7;
    /**
     * <code>optional .messages.TechType techType = 7;</code>
     */
    boolean hasTechType();
    /**
     * <code>optional .messages.TechType techType = 7;</code>
     */
    org.bwapi.proxy.messages.GameMessages.TechType getTechType();
    /**
     * <code>optional .messages.TechType techType = 7;</code>
     */
    org.bwapi.proxy.messages.GameMessages.TechTypeOrBuilder getTechTypeOrBuilder();

    // optional .messages.UpgradeType upgradeType = 8;
    /**
     * <code>optional .messages.UpgradeType upgradeType = 8;</code>
     */
    boolean hasUpgradeType();
    /**
     * <code>optional .messages.UpgradeType upgradeType = 8;</code>
     */
    org.bwapi.proxy.messages.GameMessages.UpgradeType getUpgradeType();
    /**
     * <code>optional .messages.UpgradeType upgradeType = 8;</code>
     */
    org.bwapi.proxy.messages.GameMessages.UpgradeTypeOrBuilder getUpgradeTypeOrBuilder();

    // optional int32 slot = 9;
    /**
     * <code>optional int32 slot = 9;</code>
     */
    boolean hasSlot();
    /**
     * <code>optional int32 slot = 9;</code>
     */
    int getSlot();
  }
  /**
   * Protobuf type {@code messages.Command}
   */
  public static final class Command extends
      com.google.protobuf.GeneratedMessage
      implements CommandOrBuilder {
    // Use Command.newBuilder() to construct.
    private Command(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private Command(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final Command defaultInstance;
    public static Command getDefaultInstance() {
      return defaultInstance;
    }

    public Command getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private Command(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              int rawValue = input.readEnum();
              org.bwapi.proxy.messages.Commands.CommandType value = org.bwapi.proxy.messages.Commands.CommandType.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(1, rawValue);
              } else {
                bitField0_ |= 0x00000001;
                type_ = value;
              }
              break;
            }
            case 18: {
              org.bwapi.proxy.messages.GameMessages.UnitId.Builder subBuilder = null;
              if (((bitField0_ & 0x00000002) == 0x00000002)) {
                subBuilder = self_.toBuilder();
              }
              self_ = input.readMessage(org.bwapi.proxy.messages.GameMessages.UnitId.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(self_);
                self_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000002;
              break;
            }
            case 26: {
              org.bwapi.proxy.messages.BasicTypes.Position.Builder subBuilder = null;
              if (((bitField0_ & 0x00000004) == 0x00000004)) {
                subBuilder = pos_.toBuilder();
              }
              pos_ = input.readMessage(org.bwapi.proxy.messages.BasicTypes.Position.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(pos_);
                pos_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000004;
              break;
            }
            case 34: {
              org.bwapi.proxy.messages.BasicTypes.TilePosition.Builder subBuilder = null;
              if (((bitField0_ & 0x00000008) == 0x00000008)) {
                subBuilder = tilePos_.toBuilder();
              }
              tilePos_ = input.readMessage(org.bwapi.proxy.messages.BasicTypes.TilePosition.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(tilePos_);
                tilePos_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000008;
              break;
            }
            case 42: {
              org.bwapi.proxy.messages.GameMessages.UnitId.Builder subBuilder = null;
              if (((bitField0_ & 0x00000010) == 0x00000010)) {
                subBuilder = target_.toBuilder();
              }
              target_ = input.readMessage(org.bwapi.proxy.messages.GameMessages.UnitId.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(target_);
                target_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000010;
              break;
            }
            case 50: {
              org.bwapi.proxy.messages.GameMessages.UnitType.Builder subBuilder = null;
              if (((bitField0_ & 0x00000020) == 0x00000020)) {
                subBuilder = unitType_.toBuilder();
              }
              unitType_ = input.readMessage(org.bwapi.proxy.messages.GameMessages.UnitType.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(unitType_);
                unitType_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000020;
              break;
            }
            case 58: {
              org.bwapi.proxy.messages.GameMessages.TechType.Builder subBuilder = null;
              if (((bitField0_ & 0x00000040) == 0x00000040)) {
                subBuilder = techType_.toBuilder();
              }
              techType_ = input.readMessage(org.bwapi.proxy.messages.GameMessages.TechType.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(techType_);
                techType_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000040;
              break;
            }
            case 66: {
              org.bwapi.proxy.messages.GameMessages.UpgradeType.Builder subBuilder = null;
              if (((bitField0_ & 0x00000080) == 0x00000080)) {
                subBuilder = upgradeType_.toBuilder();
              }
              upgradeType_ = input.readMessage(org.bwapi.proxy.messages.GameMessages.UpgradeType.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(upgradeType_);
                upgradeType_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000080;
              break;
            }
            case 72: {
              bitField0_ |= 0x00000100;
              slot_ = input.readInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.bwapi.proxy.messages.Commands.internal_static_messages_Command_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.bwapi.proxy.messages.Commands.internal_static_messages_Command_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.bwapi.proxy.messages.Commands.Command.class, org.bwapi.proxy.messages.Commands.Command.Builder.class);
    }

    public static com.google.protobuf.Parser<Command> PARSER =
        new com.google.protobuf.AbstractParser<Command>() {
      public Command parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Command(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<Command> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // required .messages.CommandType type = 1;
    public static final int TYPE_FIELD_NUMBER = 1;
    private org.bwapi.proxy.messages.Commands.CommandType type_;
    /**
     * <code>required .messages.CommandType type = 1;</code>
     */
    public boolean hasType() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required .messages.CommandType type = 1;</code>
     */
    public org.bwapi.proxy.messages.Commands.CommandType getType() {
      return type_;
    }

    // required .messages.UnitId self = 2;
    public static final int SELF_FIELD_NUMBER = 2;
    private org.bwapi.proxy.messages.GameMessages.UnitId self_;
    /**
     * <code>required .messages.UnitId self = 2;</code>
     */
    public boolean hasSelf() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required .messages.UnitId self = 2;</code>
     */
    public org.bwapi.proxy.messages.GameMessages.UnitId getSelf() {
      return self_;
    }
    /**
     * <code>required .messages.UnitId self = 2;</code>
     */
    public org.bwapi.proxy.messages.GameMessages.UnitIdOrBuilder getSelfOrBuilder() {
      return self_;
    }

    // optional .messages.Position pos = 3;
    public static final int POS_FIELD_NUMBER = 3;
    private org.bwapi.proxy.messages.BasicTypes.Position pos_;
    /**
     * <code>optional .messages.Position pos = 3;</code>
     */
    public boolean hasPos() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional .messages.Position pos = 3;</code>
     */
    public org.bwapi.proxy.messages.BasicTypes.Position getPos() {
      return pos_;
    }
    /**
     * <code>optional .messages.Position pos = 3;</code>
     */
    public org.bwapi.proxy.messages.BasicTypes.PositionOrBuilder getPosOrBuilder() {
      return pos_;
    }

    // optional .messages.TilePosition tilePos = 4;
    public static final int TILEPOS_FIELD_NUMBER = 4;
    private org.bwapi.proxy.messages.BasicTypes.TilePosition tilePos_;
    /**
     * <code>optional .messages.TilePosition tilePos = 4;</code>
     */
    public boolean hasTilePos() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>optional .messages.TilePosition tilePos = 4;</code>
     */
    public org.bwapi.proxy.messages.BasicTypes.TilePosition getTilePos() {
      return tilePos_;
    }
    /**
     * <code>optional .messages.TilePosition tilePos = 4;</code>
     */
    public org.bwapi.proxy.messages.BasicTypes.TilePositionOrBuilder getTilePosOrBuilder() {
      return tilePos_;
    }

    // optional .messages.UnitId target = 5;
    public static final int TARGET_FIELD_NUMBER = 5;
    private org.bwapi.proxy.messages.GameMessages.UnitId target_;
    /**
     * <code>optional .messages.UnitId target = 5;</code>
     */
    public boolean hasTarget() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    /**
     * <code>optional .messages.UnitId target = 5;</code>
     */
    public org.bwapi.proxy.messages.GameMessages.UnitId getTarget() {
      return target_;
    }
    /**
     * <code>optional .messages.UnitId target = 5;</code>
     */
    public org.bwapi.proxy.messages.GameMessages.UnitIdOrBuilder getTargetOrBuilder() {
      return target_;
    }

    // optional .messages.UnitType unitType = 6;
    public static final int UNITTYPE_FIELD_NUMBER = 6;
    private org.bwapi.proxy.messages.GameMessages.UnitType unitType_;
    /**
     * <code>optional .messages.UnitType unitType = 6;</code>
     */
    public boolean hasUnitType() {
      return ((bitField0_ & 0x00000020) == 0x00000020);
    }
    /**
     * <code>optional .messages.UnitType unitType = 6;</code>
     */
    public org.bwapi.proxy.messages.GameMessages.UnitType getUnitType() {
      return unitType_;
    }
    /**
     * <code>optional .messages.UnitType unitType = 6;</code>
     */
    public org.bwapi.proxy.messages.GameMessages.UnitTypeOrBuilder getUnitTypeOrBuilder() {
      return unitType_;
    }

    // optional .messages.TechType techType = 7;
    public static final int TECHTYPE_FIELD_NUMBER = 7;
    private org.bwapi.proxy.messages.GameMessages.TechType techType_;
    /**
     * <code>optional .messages.TechType techType = 7;</code>
     */
    public boolean hasTechType() {
      return ((bitField0_ & 0x00000040) == 0x00000040);
    }
    /**
     * <code>optional .messages.TechType techType = 7;</code>
     */
    public org.bwapi.proxy.messages.GameMessages.TechType getTechType() {
      return techType_;
    }
    /**
     * <code>optional .messages.TechType techType = 7;</code>
     */
    public org.bwapi.proxy.messages.GameMessages.TechTypeOrBuilder getTechTypeOrBuilder() {
      return techType_;
    }

    // optional .messages.UpgradeType upgradeType = 8;
    public static final int UPGRADETYPE_FIELD_NUMBER = 8;
    private org.bwapi.proxy.messages.GameMessages.UpgradeType upgradeType_;
    /**
     * <code>optional .messages.UpgradeType upgradeType = 8;</code>
     */
    public boolean hasUpgradeType() {
      return ((bitField0_ & 0x00000080) == 0x00000080);
    }
    /**
     * <code>optional .messages.UpgradeType upgradeType = 8;</code>
     */
    public org.bwapi.proxy.messages.GameMessages.UpgradeType getUpgradeType() {
      return upgradeType_;
    }
    /**
     * <code>optional .messages.UpgradeType upgradeType = 8;</code>
     */
    public org.bwapi.proxy.messages.GameMessages.UpgradeTypeOrBuilder getUpgradeTypeOrBuilder() {
      return upgradeType_;
    }

    // optional int32 slot = 9;
    public static final int SLOT_FIELD_NUMBER = 9;
    private int slot_;
    /**
     * <code>optional int32 slot = 9;</code>
     */
    public boolean hasSlot() {
      return ((bitField0_ & 0x00000100) == 0x00000100);
    }
    /**
     * <code>optional int32 slot = 9;</code>
     */
    public int getSlot() {
      return slot_;
    }

    private void initFields() {
      type_ = org.bwapi.proxy.messages.Commands.CommandType.none;
      self_ = org.bwapi.proxy.messages.GameMessages.UnitId.getDefaultInstance();
      pos_ = org.bwapi.proxy.messages.BasicTypes.Position.getDefaultInstance();
      tilePos_ = org.bwapi.proxy.messages.BasicTypes.TilePosition.getDefaultInstance();
      target_ = org.bwapi.proxy.messages.GameMessages.UnitId.getDefaultInstance();
      unitType_ = org.bwapi.proxy.messages.GameMessages.UnitType.getDefaultInstance();
      techType_ = org.bwapi.proxy.messages.GameMessages.TechType.getDefaultInstance();
      upgradeType_ = org.bwapi.proxy.messages.GameMessages.UpgradeType.getDefaultInstance();
      slot_ = 0;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasType()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasSelf()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!getSelf().isInitialized()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (hasPos()) {
        if (!getPos().isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      if (hasTilePos()) {
        if (!getTilePos().isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      if (hasTarget()) {
        if (!getTarget().isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      if (hasUnitType()) {
        if (!getUnitType().isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      if (hasTechType()) {
        if (!getTechType().isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      if (hasUpgradeType()) {
        if (!getUpgradeType().isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeEnum(1, type_.getNumber());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeMessage(2, self_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeMessage(3, pos_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeMessage(4, tilePos_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeMessage(5, target_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        output.writeMessage(6, unitType_);
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        output.writeMessage(7, techType_);
      }
      if (((bitField0_ & 0x00000080) == 0x00000080)) {
        output.writeMessage(8, upgradeType_);
      }
      if (((bitField0_ & 0x00000100) == 0x00000100)) {
        output.writeInt32(9, slot_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, type_.getNumber());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, self_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, pos_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(4, tilePos_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(5, target_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(6, unitType_);
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(7, techType_);
      }
      if (((bitField0_ & 0x00000080) == 0x00000080)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(8, upgradeType_);
      }
      if (((bitField0_ & 0x00000100) == 0x00000100)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(9, slot_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static org.bwapi.proxy.messages.Commands.Command parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.bwapi.proxy.messages.Commands.Command parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.bwapi.proxy.messages.Commands.Command parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.bwapi.proxy.messages.Commands.Command parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.bwapi.proxy.messages.Commands.Command parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static org.bwapi.proxy.messages.Commands.Command parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static org.bwapi.proxy.messages.Commands.Command parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static org.bwapi.proxy.messages.Commands.Command parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static org.bwapi.proxy.messages.Commands.Command parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static org.bwapi.proxy.messages.Commands.Command parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(org.bwapi.proxy.messages.Commands.Command prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code messages.Command}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements org.bwapi.proxy.messages.Commands.CommandOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.bwapi.proxy.messages.Commands.internal_static_messages_Command_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.bwapi.proxy.messages.Commands.internal_static_messages_Command_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                org.bwapi.proxy.messages.Commands.Command.class, org.bwapi.proxy.messages.Commands.Command.Builder.class);
      }

      // Construct using org.bwapi.proxy.messages.Commands.Command.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getSelfFieldBuilder();
          getPosFieldBuilder();
          getTilePosFieldBuilder();
          getTargetFieldBuilder();
          getUnitTypeFieldBuilder();
          getTechTypeFieldBuilder();
          getUpgradeTypeFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        type_ = org.bwapi.proxy.messages.Commands.CommandType.none;
        bitField0_ = (bitField0_ & ~0x00000001);
        if (selfBuilder_ == null) {
          self_ = org.bwapi.proxy.messages.GameMessages.UnitId.getDefaultInstance();
        } else {
          selfBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000002);
        if (posBuilder_ == null) {
          pos_ = org.bwapi.proxy.messages.BasicTypes.Position.getDefaultInstance();
        } else {
          posBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000004);
        if (tilePosBuilder_ == null) {
          tilePos_ = org.bwapi.proxy.messages.BasicTypes.TilePosition.getDefaultInstance();
        } else {
          tilePosBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000008);
        if (targetBuilder_ == null) {
          target_ = org.bwapi.proxy.messages.GameMessages.UnitId.getDefaultInstance();
        } else {
          targetBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000010);
        if (unitTypeBuilder_ == null) {
          unitType_ = org.bwapi.proxy.messages.GameMessages.UnitType.getDefaultInstance();
        } else {
          unitTypeBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000020);
        if (techTypeBuilder_ == null) {
          techType_ = org.bwapi.proxy.messages.GameMessages.TechType.getDefaultInstance();
        } else {
          techTypeBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000040);
        if (upgradeTypeBuilder_ == null) {
          upgradeType_ = org.bwapi.proxy.messages.GameMessages.UpgradeType.getDefaultInstance();
        } else {
          upgradeTypeBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000080);
        slot_ = 0;
        bitField0_ = (bitField0_ & ~0x00000100);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.bwapi.proxy.messages.Commands.internal_static_messages_Command_descriptor;
      }

      public org.bwapi.proxy.messages.Commands.Command getDefaultInstanceForType() {
        return org.bwapi.proxy.messages.Commands.Command.getDefaultInstance();
      }

      public org.bwapi.proxy.messages.Commands.Command build() {
        org.bwapi.proxy.messages.Commands.Command result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public org.bwapi.proxy.messages.Commands.Command buildPartial() {
        org.bwapi.proxy.messages.Commands.Command result = new org.bwapi.proxy.messages.Commands.Command(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.type_ = type_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        if (selfBuilder_ == null) {
          result.self_ = self_;
        } else {
          result.self_ = selfBuilder_.build();
        }
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        if (posBuilder_ == null) {
          result.pos_ = pos_;
        } else {
          result.pos_ = posBuilder_.build();
        }
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        if (tilePosBuilder_ == null) {
          result.tilePos_ = tilePos_;
        } else {
          result.tilePos_ = tilePosBuilder_.build();
        }
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        if (targetBuilder_ == null) {
          result.target_ = target_;
        } else {
          result.target_ = targetBuilder_.build();
        }
        if (((from_bitField0_ & 0x00000020) == 0x00000020)) {
          to_bitField0_ |= 0x00000020;
        }
        if (unitTypeBuilder_ == null) {
          result.unitType_ = unitType_;
        } else {
          result.unitType_ = unitTypeBuilder_.build();
        }
        if (((from_bitField0_ & 0x00000040) == 0x00000040)) {
          to_bitField0_ |= 0x00000040;
        }
        if (techTypeBuilder_ == null) {
          result.techType_ = techType_;
        } else {
          result.techType_ = techTypeBuilder_.build();
        }
        if (((from_bitField0_ & 0x00000080) == 0x00000080)) {
          to_bitField0_ |= 0x00000080;
        }
        if (upgradeTypeBuilder_ == null) {
          result.upgradeType_ = upgradeType_;
        } else {
          result.upgradeType_ = upgradeTypeBuilder_.build();
        }
        if (((from_bitField0_ & 0x00000100) == 0x00000100)) {
          to_bitField0_ |= 0x00000100;
        }
        result.slot_ = slot_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.bwapi.proxy.messages.Commands.Command) {
          return mergeFrom((org.bwapi.proxy.messages.Commands.Command)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(org.bwapi.proxy.messages.Commands.Command other) {
        if (other == org.bwapi.proxy.messages.Commands.Command.getDefaultInstance()) return this;
        if (other.hasType()) {
          setType(other.getType());
        }
        if (other.hasSelf()) {
          mergeSelf(other.getSelf());
        }
        if (other.hasPos()) {
          mergePos(other.getPos());
        }
        if (other.hasTilePos()) {
          mergeTilePos(other.getTilePos());
        }
        if (other.hasTarget()) {
          mergeTarget(other.getTarget());
        }
        if (other.hasUnitType()) {
          mergeUnitType(other.getUnitType());
        }
        if (other.hasTechType()) {
          mergeTechType(other.getTechType());
        }
        if (other.hasUpgradeType()) {
          mergeUpgradeType(other.getUpgradeType());
        }
        if (other.hasSlot()) {
          setSlot(other.getSlot());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasType()) {
          
          return false;
        }
        if (!hasSelf()) {
          
          return false;
        }
        if (!getSelf().isInitialized()) {
          
          return false;
        }
        if (hasPos()) {
          if (!getPos().isInitialized()) {
            
            return false;
          }
        }
        if (hasTilePos()) {
          if (!getTilePos().isInitialized()) {
            
            return false;
          }
        }
        if (hasTarget()) {
          if (!getTarget().isInitialized()) {
            
            return false;
          }
        }
        if (hasUnitType()) {
          if (!getUnitType().isInitialized()) {
            
            return false;
          }
        }
        if (hasTechType()) {
          if (!getTechType().isInitialized()) {
            
            return false;
          }
        }
        if (hasUpgradeType()) {
          if (!getUpgradeType().isInitialized()) {
            
            return false;
          }
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        org.bwapi.proxy.messages.Commands.Command parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (org.bwapi.proxy.messages.Commands.Command) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required .messages.CommandType type = 1;
      private org.bwapi.proxy.messages.Commands.CommandType type_ = org.bwapi.proxy.messages.Commands.CommandType.none;
      /**
       * <code>required .messages.CommandType type = 1;</code>
       */
      public boolean hasType() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required .messages.CommandType type = 1;</code>
       */
      public org.bwapi.proxy.messages.Commands.CommandType getType() {
        return type_;
      }
      /**
       * <code>required .messages.CommandType type = 1;</code>
       */
      public Builder setType(org.bwapi.proxy.messages.Commands.CommandType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000001;
        type_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required .messages.CommandType type = 1;</code>
       */
      public Builder clearType() {
        bitField0_ = (bitField0_ & ~0x00000001);
        type_ = org.bwapi.proxy.messages.Commands.CommandType.none;
        onChanged();
        return this;
      }

      // required .messages.UnitId self = 2;
      private org.bwapi.proxy.messages.GameMessages.UnitId self_ = org.bwapi.proxy.messages.GameMessages.UnitId.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          org.bwapi.proxy.messages.GameMessages.UnitId, org.bwapi.proxy.messages.GameMessages.UnitId.Builder, org.bwapi.proxy.messages.GameMessages.UnitIdOrBuilder> selfBuilder_;
      /**
       * <code>required .messages.UnitId self = 2;</code>
       */
      public boolean hasSelf() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required .messages.UnitId self = 2;</code>
       */
      public org.bwapi.proxy.messages.GameMessages.UnitId getSelf() {
        if (selfBuilder_ == null) {
          return self_;
        } else {
          return selfBuilder_.getMessage();
        }
      }
      /**
       * <code>required .messages.UnitId self = 2;</code>
       */
      public Builder setSelf(org.bwapi.proxy.messages.GameMessages.UnitId value) {
        if (selfBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          self_ = value;
          onChanged();
        } else {
          selfBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      /**
       * <code>required .messages.UnitId self = 2;</code>
       */
      public Builder setSelf(
          org.bwapi.proxy.messages.GameMessages.UnitId.Builder builderForValue) {
        if (selfBuilder_ == null) {
          self_ = builderForValue.build();
          onChanged();
        } else {
          selfBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      /**
       * <code>required .messages.UnitId self = 2;</code>
       */
      public Builder mergeSelf(org.bwapi.proxy.messages.GameMessages.UnitId value) {
        if (selfBuilder_ == null) {
          if (((bitField0_ & 0x00000002) == 0x00000002) &&
              self_ != org.bwapi.proxy.messages.GameMessages.UnitId.getDefaultInstance()) {
            self_ =
              org.bwapi.proxy.messages.GameMessages.UnitId.newBuilder(self_).mergeFrom(value).buildPartial();
          } else {
            self_ = value;
          }
          onChanged();
        } else {
          selfBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      /**
       * <code>required .messages.UnitId self = 2;</code>
       */
      public Builder clearSelf() {
        if (selfBuilder_ == null) {
          self_ = org.bwapi.proxy.messages.GameMessages.UnitId.getDefaultInstance();
          onChanged();
        } else {
          selfBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }
      /**
       * <code>required .messages.UnitId self = 2;</code>
       */
      public org.bwapi.proxy.messages.GameMessages.UnitId.Builder getSelfBuilder() {
        bitField0_ |= 0x00000002;
        onChanged();
        return getSelfFieldBuilder().getBuilder();
      }
      /**
       * <code>required .messages.UnitId self = 2;</code>
       */
      public org.bwapi.proxy.messages.GameMessages.UnitIdOrBuilder getSelfOrBuilder() {
        if (selfBuilder_ != null) {
          return selfBuilder_.getMessageOrBuilder();
        } else {
          return self_;
        }
      }
      /**
       * <code>required .messages.UnitId self = 2;</code>
       */
      private com.google.protobuf.SingleFieldBuilder<
          org.bwapi.proxy.messages.GameMessages.UnitId, org.bwapi.proxy.messages.GameMessages.UnitId.Builder, org.bwapi.proxy.messages.GameMessages.UnitIdOrBuilder> 
          getSelfFieldBuilder() {
        if (selfBuilder_ == null) {
          selfBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              org.bwapi.proxy.messages.GameMessages.UnitId, org.bwapi.proxy.messages.GameMessages.UnitId.Builder, org.bwapi.proxy.messages.GameMessages.UnitIdOrBuilder>(
                  self_,
                  getParentForChildren(),
                  isClean());
          self_ = null;
        }
        return selfBuilder_;
      }

      // optional .messages.Position pos = 3;
      private org.bwapi.proxy.messages.BasicTypes.Position pos_ = org.bwapi.proxy.messages.BasicTypes.Position.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          org.bwapi.proxy.messages.BasicTypes.Position, org.bwapi.proxy.messages.BasicTypes.Position.Builder, org.bwapi.proxy.messages.BasicTypes.PositionOrBuilder> posBuilder_;
      /**
       * <code>optional .messages.Position pos = 3;</code>
       */
      public boolean hasPos() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional .messages.Position pos = 3;</code>
       */
      public org.bwapi.proxy.messages.BasicTypes.Position getPos() {
        if (posBuilder_ == null) {
          return pos_;
        } else {
          return posBuilder_.getMessage();
        }
      }
      /**
       * <code>optional .messages.Position pos = 3;</code>
       */
      public Builder setPos(org.bwapi.proxy.messages.BasicTypes.Position value) {
        if (posBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          pos_ = value;
          onChanged();
        } else {
          posBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000004;
        return this;
      }
      /**
       * <code>optional .messages.Position pos = 3;</code>
       */
      public Builder setPos(
          org.bwapi.proxy.messages.BasicTypes.Position.Builder builderForValue) {
        if (posBuilder_ == null) {
          pos_ = builderForValue.build();
          onChanged();
        } else {
          posBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000004;
        return this;
      }
      /**
       * <code>optional .messages.Position pos = 3;</code>
       */
      public Builder mergePos(org.bwapi.proxy.messages.BasicTypes.Position value) {
        if (posBuilder_ == null) {
          if (((bitField0_ & 0x00000004) == 0x00000004) &&
              pos_ != org.bwapi.proxy.messages.BasicTypes.Position.getDefaultInstance()) {
            pos_ =
              org.bwapi.proxy.messages.BasicTypes.Position.newBuilder(pos_).mergeFrom(value).buildPartial();
          } else {
            pos_ = value;
          }
          onChanged();
        } else {
          posBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000004;
        return this;
      }
      /**
       * <code>optional .messages.Position pos = 3;</code>
       */
      public Builder clearPos() {
        if (posBuilder_ == null) {
          pos_ = org.bwapi.proxy.messages.BasicTypes.Position.getDefaultInstance();
          onChanged();
        } else {
          posBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }
      /**
       * <code>optional .messages.Position pos = 3;</code>
       */
      public org.bwapi.proxy.messages.BasicTypes.Position.Builder getPosBuilder() {
        bitField0_ |= 0x00000004;
        onChanged();
        return getPosFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .messages.Position pos = 3;</code>
       */
      public org.bwapi.proxy.messages.BasicTypes.PositionOrBuilder getPosOrBuilder() {
        if (posBuilder_ != null) {
          return posBuilder_.getMessageOrBuilder();
        } else {
          return pos_;
        }
      }
      /**
       * <code>optional .messages.Position pos = 3;</code>
       */
      private com.google.protobuf.SingleFieldBuilder<
          org.bwapi.proxy.messages.BasicTypes.Position, org.bwapi.proxy.messages.BasicTypes.Position.Builder, org.bwapi.proxy.messages.BasicTypes.PositionOrBuilder> 
          getPosFieldBuilder() {
        if (posBuilder_ == null) {
          posBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              org.bwapi.proxy.messages.BasicTypes.Position, org.bwapi.proxy.messages.BasicTypes.Position.Builder, org.bwapi.proxy.messages.BasicTypes.PositionOrBuilder>(
                  pos_,
                  getParentForChildren(),
                  isClean());
          pos_ = null;
        }
        return posBuilder_;
      }

      // optional .messages.TilePosition tilePos = 4;
      private org.bwapi.proxy.messages.BasicTypes.TilePosition tilePos_ = org.bwapi.proxy.messages.BasicTypes.TilePosition.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          org.bwapi.proxy.messages.BasicTypes.TilePosition, org.bwapi.proxy.messages.BasicTypes.TilePosition.Builder, org.bwapi.proxy.messages.BasicTypes.TilePositionOrBuilder> tilePosBuilder_;
      /**
       * <code>optional .messages.TilePosition tilePos = 4;</code>
       */
      public boolean hasTilePos() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>optional .messages.TilePosition tilePos = 4;</code>
       */
      public org.bwapi.proxy.messages.BasicTypes.TilePosition getTilePos() {
        if (tilePosBuilder_ == null) {
          return tilePos_;
        } else {
          return tilePosBuilder_.getMessage();
        }
      }
      /**
       * <code>optional .messages.TilePosition tilePos = 4;</code>
       */
      public Builder setTilePos(org.bwapi.proxy.messages.BasicTypes.TilePosition value) {
        if (tilePosBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          tilePos_ = value;
          onChanged();
        } else {
          tilePosBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000008;
        return this;
      }
      /**
       * <code>optional .messages.TilePosition tilePos = 4;</code>
       */
      public Builder setTilePos(
          org.bwapi.proxy.messages.BasicTypes.TilePosition.Builder builderForValue) {
        if (tilePosBuilder_ == null) {
          tilePos_ = builderForValue.build();
          onChanged();
        } else {
          tilePosBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000008;
        return this;
      }
      /**
       * <code>optional .messages.TilePosition tilePos = 4;</code>
       */
      public Builder mergeTilePos(org.bwapi.proxy.messages.BasicTypes.TilePosition value) {
        if (tilePosBuilder_ == null) {
          if (((bitField0_ & 0x00000008) == 0x00000008) &&
              tilePos_ != org.bwapi.proxy.messages.BasicTypes.TilePosition.getDefaultInstance()) {
            tilePos_ =
              org.bwapi.proxy.messages.BasicTypes.TilePosition.newBuilder(tilePos_).mergeFrom(value).buildPartial();
          } else {
            tilePos_ = value;
          }
          onChanged();
        } else {
          tilePosBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000008;
        return this;
      }
      /**
       * <code>optional .messages.TilePosition tilePos = 4;</code>
       */
      public Builder clearTilePos() {
        if (tilePosBuilder_ == null) {
          tilePos_ = org.bwapi.proxy.messages.BasicTypes.TilePosition.getDefaultInstance();
          onChanged();
        } else {
          tilePosBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000008);
        return this;
      }
      /**
       * <code>optional .messages.TilePosition tilePos = 4;</code>
       */
      public org.bwapi.proxy.messages.BasicTypes.TilePosition.Builder getTilePosBuilder() {
        bitField0_ |= 0x00000008;
        onChanged();
        return getTilePosFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .messages.TilePosition tilePos = 4;</code>
       */
      public org.bwapi.proxy.messages.BasicTypes.TilePositionOrBuilder getTilePosOrBuilder() {
        if (tilePosBuilder_ != null) {
          return tilePosBuilder_.getMessageOrBuilder();
        } else {
          return tilePos_;
        }
      }
      /**
       * <code>optional .messages.TilePosition tilePos = 4;</code>
       */
      private com.google.protobuf.SingleFieldBuilder<
          org.bwapi.proxy.messages.BasicTypes.TilePosition, org.bwapi.proxy.messages.BasicTypes.TilePosition.Builder, org.bwapi.proxy.messages.BasicTypes.TilePositionOrBuilder> 
          getTilePosFieldBuilder() {
        if (tilePosBuilder_ == null) {
          tilePosBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              org.bwapi.proxy.messages.BasicTypes.TilePosition, org.bwapi.proxy.messages.BasicTypes.TilePosition.Builder, org.bwapi.proxy.messages.BasicTypes.TilePositionOrBuilder>(
                  tilePos_,
                  getParentForChildren(),
                  isClean());
          tilePos_ = null;
        }
        return tilePosBuilder_;
      }

      // optional .messages.UnitId target = 5;
      private org.bwapi.proxy.messages.GameMessages.UnitId target_ = org.bwapi.proxy.messages.GameMessages.UnitId.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          org.bwapi.proxy.messages.GameMessages.UnitId, org.bwapi.proxy.messages.GameMessages.UnitId.Builder, org.bwapi.proxy.messages.GameMessages.UnitIdOrBuilder> targetBuilder_;
      /**
       * <code>optional .messages.UnitId target = 5;</code>
       */
      public boolean hasTarget() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      /**
       * <code>optional .messages.UnitId target = 5;</code>
       */
      public org.bwapi.proxy.messages.GameMessages.UnitId getTarget() {
        if (targetBuilder_ == null) {
          return target_;
        } else {
          return targetBuilder_.getMessage();
        }
      }
      /**
       * <code>optional .messages.UnitId target = 5;</code>
       */
      public Builder setTarget(org.bwapi.proxy.messages.GameMessages.UnitId value) {
        if (targetBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          target_ = value;
          onChanged();
        } else {
          targetBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000010;
        return this;
      }
      /**
       * <code>optional .messages.UnitId target = 5;</code>
       */
      public Builder setTarget(
          org.bwapi.proxy.messages.GameMessages.UnitId.Builder builderForValue) {
        if (targetBuilder_ == null) {
          target_ = builderForValue.build();
          onChanged();
        } else {
          targetBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000010;
        return this;
      }
      /**
       * <code>optional .messages.UnitId target = 5;</code>
       */
      public Builder mergeTarget(org.bwapi.proxy.messages.GameMessages.UnitId value) {
        if (targetBuilder_ == null) {
          if (((bitField0_ & 0x00000010) == 0x00000010) &&
              target_ != org.bwapi.proxy.messages.GameMessages.UnitId.getDefaultInstance()) {
            target_ =
              org.bwapi.proxy.messages.GameMessages.UnitId.newBuilder(target_).mergeFrom(value).buildPartial();
          } else {
            target_ = value;
          }
          onChanged();
        } else {
          targetBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000010;
        return this;
      }
      /**
       * <code>optional .messages.UnitId target = 5;</code>
       */
      public Builder clearTarget() {
        if (targetBuilder_ == null) {
          target_ = org.bwapi.proxy.messages.GameMessages.UnitId.getDefaultInstance();
          onChanged();
        } else {
          targetBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000010);
        return this;
      }
      /**
       * <code>optional .messages.UnitId target = 5;</code>
       */
      public org.bwapi.proxy.messages.GameMessages.UnitId.Builder getTargetBuilder() {
        bitField0_ |= 0x00000010;
        onChanged();
        return getTargetFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .messages.UnitId target = 5;</code>
       */
      public org.bwapi.proxy.messages.GameMessages.UnitIdOrBuilder getTargetOrBuilder() {
        if (targetBuilder_ != null) {
          return targetBuilder_.getMessageOrBuilder();
        } else {
          return target_;
        }
      }
      /**
       * <code>optional .messages.UnitId target = 5;</code>
       */
      private com.google.protobuf.SingleFieldBuilder<
          org.bwapi.proxy.messages.GameMessages.UnitId, org.bwapi.proxy.messages.GameMessages.UnitId.Builder, org.bwapi.proxy.messages.GameMessages.UnitIdOrBuilder> 
          getTargetFieldBuilder() {
        if (targetBuilder_ == null) {
          targetBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              org.bwapi.proxy.messages.GameMessages.UnitId, org.bwapi.proxy.messages.GameMessages.UnitId.Builder, org.bwapi.proxy.messages.GameMessages.UnitIdOrBuilder>(
                  target_,
                  getParentForChildren(),
                  isClean());
          target_ = null;
        }
        return targetBuilder_;
      }

      // optional .messages.UnitType unitType = 6;
      private org.bwapi.proxy.messages.GameMessages.UnitType unitType_ = org.bwapi.proxy.messages.GameMessages.UnitType.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          org.bwapi.proxy.messages.GameMessages.UnitType, org.bwapi.proxy.messages.GameMessages.UnitType.Builder, org.bwapi.proxy.messages.GameMessages.UnitTypeOrBuilder> unitTypeBuilder_;
      /**
       * <code>optional .messages.UnitType unitType = 6;</code>
       */
      public boolean hasUnitType() {
        return ((bitField0_ & 0x00000020) == 0x00000020);
      }
      /**
       * <code>optional .messages.UnitType unitType = 6;</code>
       */
      public org.bwapi.proxy.messages.GameMessages.UnitType getUnitType() {
        if (unitTypeBuilder_ == null) {
          return unitType_;
        } else {
          return unitTypeBuilder_.getMessage();
        }
      }
      /**
       * <code>optional .messages.UnitType unitType = 6;</code>
       */
      public Builder setUnitType(org.bwapi.proxy.messages.GameMessages.UnitType value) {
        if (unitTypeBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          unitType_ = value;
          onChanged();
        } else {
          unitTypeBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000020;
        return this;
      }
      /**
       * <code>optional .messages.UnitType unitType = 6;</code>
       */
      public Builder setUnitType(
          org.bwapi.proxy.messages.GameMessages.UnitType.Builder builderForValue) {
        if (unitTypeBuilder_ == null) {
          unitType_ = builderForValue.build();
          onChanged();
        } else {
          unitTypeBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000020;
        return this;
      }
      /**
       * <code>optional .messages.UnitType unitType = 6;</code>
       */
      public Builder mergeUnitType(org.bwapi.proxy.messages.GameMessages.UnitType value) {
        if (unitTypeBuilder_ == null) {
          if (((bitField0_ & 0x00000020) == 0x00000020) &&
              unitType_ != org.bwapi.proxy.messages.GameMessages.UnitType.getDefaultInstance()) {
            unitType_ =
              org.bwapi.proxy.messages.GameMessages.UnitType.newBuilder(unitType_).mergeFrom(value).buildPartial();
          } else {
            unitType_ = value;
          }
          onChanged();
        } else {
          unitTypeBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000020;
        return this;
      }
      /**
       * <code>optional .messages.UnitType unitType = 6;</code>
       */
      public Builder clearUnitType() {
        if (unitTypeBuilder_ == null) {
          unitType_ = org.bwapi.proxy.messages.GameMessages.UnitType.getDefaultInstance();
          onChanged();
        } else {
          unitTypeBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000020);
        return this;
      }
      /**
       * <code>optional .messages.UnitType unitType = 6;</code>
       */
      public org.bwapi.proxy.messages.GameMessages.UnitType.Builder getUnitTypeBuilder() {
        bitField0_ |= 0x00000020;
        onChanged();
        return getUnitTypeFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .messages.UnitType unitType = 6;</code>
       */
      public org.bwapi.proxy.messages.GameMessages.UnitTypeOrBuilder getUnitTypeOrBuilder() {
        if (unitTypeBuilder_ != null) {
          return unitTypeBuilder_.getMessageOrBuilder();
        } else {
          return unitType_;
        }
      }
      /**
       * <code>optional .messages.UnitType unitType = 6;</code>
       */
      private com.google.protobuf.SingleFieldBuilder<
          org.bwapi.proxy.messages.GameMessages.UnitType, org.bwapi.proxy.messages.GameMessages.UnitType.Builder, org.bwapi.proxy.messages.GameMessages.UnitTypeOrBuilder> 
          getUnitTypeFieldBuilder() {
        if (unitTypeBuilder_ == null) {
          unitTypeBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              org.bwapi.proxy.messages.GameMessages.UnitType, org.bwapi.proxy.messages.GameMessages.UnitType.Builder, org.bwapi.proxy.messages.GameMessages.UnitTypeOrBuilder>(
                  unitType_,
                  getParentForChildren(),
                  isClean());
          unitType_ = null;
        }
        return unitTypeBuilder_;
      }

      // optional .messages.TechType techType = 7;
      private org.bwapi.proxy.messages.GameMessages.TechType techType_ = org.bwapi.proxy.messages.GameMessages.TechType.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          org.bwapi.proxy.messages.GameMessages.TechType, org.bwapi.proxy.messages.GameMessages.TechType.Builder, org.bwapi.proxy.messages.GameMessages.TechTypeOrBuilder> techTypeBuilder_;
      /**
       * <code>optional .messages.TechType techType = 7;</code>
       */
      public boolean hasTechType() {
        return ((bitField0_ & 0x00000040) == 0x00000040);
      }
      /**
       * <code>optional .messages.TechType techType = 7;</code>
       */
      public org.bwapi.proxy.messages.GameMessages.TechType getTechType() {
        if (techTypeBuilder_ == null) {
          return techType_;
        } else {
          return techTypeBuilder_.getMessage();
        }
      }
      /**
       * <code>optional .messages.TechType techType = 7;</code>
       */
      public Builder setTechType(org.bwapi.proxy.messages.GameMessages.TechType value) {
        if (techTypeBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          techType_ = value;
          onChanged();
        } else {
          techTypeBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000040;
        return this;
      }
      /**
       * <code>optional .messages.TechType techType = 7;</code>
       */
      public Builder setTechType(
          org.bwapi.proxy.messages.GameMessages.TechType.Builder builderForValue) {
        if (techTypeBuilder_ == null) {
          techType_ = builderForValue.build();
          onChanged();
        } else {
          techTypeBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000040;
        return this;
      }
      /**
       * <code>optional .messages.TechType techType = 7;</code>
       */
      public Builder mergeTechType(org.bwapi.proxy.messages.GameMessages.TechType value) {
        if (techTypeBuilder_ == null) {
          if (((bitField0_ & 0x00000040) == 0x00000040) &&
              techType_ != org.bwapi.proxy.messages.GameMessages.TechType.getDefaultInstance()) {
            techType_ =
              org.bwapi.proxy.messages.GameMessages.TechType.newBuilder(techType_).mergeFrom(value).buildPartial();
          } else {
            techType_ = value;
          }
          onChanged();
        } else {
          techTypeBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000040;
        return this;
      }
      /**
       * <code>optional .messages.TechType techType = 7;</code>
       */
      public Builder clearTechType() {
        if (techTypeBuilder_ == null) {
          techType_ = org.bwapi.proxy.messages.GameMessages.TechType.getDefaultInstance();
          onChanged();
        } else {
          techTypeBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000040);
        return this;
      }
      /**
       * <code>optional .messages.TechType techType = 7;</code>
       */
      public org.bwapi.proxy.messages.GameMessages.TechType.Builder getTechTypeBuilder() {
        bitField0_ |= 0x00000040;
        onChanged();
        return getTechTypeFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .messages.TechType techType = 7;</code>
       */
      public org.bwapi.proxy.messages.GameMessages.TechTypeOrBuilder getTechTypeOrBuilder() {
        if (techTypeBuilder_ != null) {
          return techTypeBuilder_.getMessageOrBuilder();
        } else {
          return techType_;
        }
      }
      /**
       * <code>optional .messages.TechType techType = 7;</code>
       */
      private com.google.protobuf.SingleFieldBuilder<
          org.bwapi.proxy.messages.GameMessages.TechType, org.bwapi.proxy.messages.GameMessages.TechType.Builder, org.bwapi.proxy.messages.GameMessages.TechTypeOrBuilder> 
          getTechTypeFieldBuilder() {
        if (techTypeBuilder_ == null) {
          techTypeBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              org.bwapi.proxy.messages.GameMessages.TechType, org.bwapi.proxy.messages.GameMessages.TechType.Builder, org.bwapi.proxy.messages.GameMessages.TechTypeOrBuilder>(
                  techType_,
                  getParentForChildren(),
                  isClean());
          techType_ = null;
        }
        return techTypeBuilder_;
      }

      // optional .messages.UpgradeType upgradeType = 8;
      private org.bwapi.proxy.messages.GameMessages.UpgradeType upgradeType_ = org.bwapi.proxy.messages.GameMessages.UpgradeType.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          org.bwapi.proxy.messages.GameMessages.UpgradeType, org.bwapi.proxy.messages.GameMessages.UpgradeType.Builder, org.bwapi.proxy.messages.GameMessages.UpgradeTypeOrBuilder> upgradeTypeBuilder_;
      /**
       * <code>optional .messages.UpgradeType upgradeType = 8;</code>
       */
      public boolean hasUpgradeType() {
        return ((bitField0_ & 0x00000080) == 0x00000080);
      }
      /**
       * <code>optional .messages.UpgradeType upgradeType = 8;</code>
       */
      public org.bwapi.proxy.messages.GameMessages.UpgradeType getUpgradeType() {
        if (upgradeTypeBuilder_ == null) {
          return upgradeType_;
        } else {
          return upgradeTypeBuilder_.getMessage();
        }
      }
      /**
       * <code>optional .messages.UpgradeType upgradeType = 8;</code>
       */
      public Builder setUpgradeType(org.bwapi.proxy.messages.GameMessages.UpgradeType value) {
        if (upgradeTypeBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          upgradeType_ = value;
          onChanged();
        } else {
          upgradeTypeBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000080;
        return this;
      }
      /**
       * <code>optional .messages.UpgradeType upgradeType = 8;</code>
       */
      public Builder setUpgradeType(
          org.bwapi.proxy.messages.GameMessages.UpgradeType.Builder builderForValue) {
        if (upgradeTypeBuilder_ == null) {
          upgradeType_ = builderForValue.build();
          onChanged();
        } else {
          upgradeTypeBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000080;
        return this;
      }
      /**
       * <code>optional .messages.UpgradeType upgradeType = 8;</code>
       */
      public Builder mergeUpgradeType(org.bwapi.proxy.messages.GameMessages.UpgradeType value) {
        if (upgradeTypeBuilder_ == null) {
          if (((bitField0_ & 0x00000080) == 0x00000080) &&
              upgradeType_ != org.bwapi.proxy.messages.GameMessages.UpgradeType.getDefaultInstance()) {
            upgradeType_ =
              org.bwapi.proxy.messages.GameMessages.UpgradeType.newBuilder(upgradeType_).mergeFrom(value).buildPartial();
          } else {
            upgradeType_ = value;
          }
          onChanged();
        } else {
          upgradeTypeBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000080;
        return this;
      }
      /**
       * <code>optional .messages.UpgradeType upgradeType = 8;</code>
       */
      public Builder clearUpgradeType() {
        if (upgradeTypeBuilder_ == null) {
          upgradeType_ = org.bwapi.proxy.messages.GameMessages.UpgradeType.getDefaultInstance();
          onChanged();
        } else {
          upgradeTypeBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000080);
        return this;
      }
      /**
       * <code>optional .messages.UpgradeType upgradeType = 8;</code>
       */
      public org.bwapi.proxy.messages.GameMessages.UpgradeType.Builder getUpgradeTypeBuilder() {
        bitField0_ |= 0x00000080;
        onChanged();
        return getUpgradeTypeFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .messages.UpgradeType upgradeType = 8;</code>
       */
      public org.bwapi.proxy.messages.GameMessages.UpgradeTypeOrBuilder getUpgradeTypeOrBuilder() {
        if (upgradeTypeBuilder_ != null) {
          return upgradeTypeBuilder_.getMessageOrBuilder();
        } else {
          return upgradeType_;
        }
      }
      /**
       * <code>optional .messages.UpgradeType upgradeType = 8;</code>
       */
      private com.google.protobuf.SingleFieldBuilder<
          org.bwapi.proxy.messages.GameMessages.UpgradeType, org.bwapi.proxy.messages.GameMessages.UpgradeType.Builder, org.bwapi.proxy.messages.GameMessages.UpgradeTypeOrBuilder> 
          getUpgradeTypeFieldBuilder() {
        if (upgradeTypeBuilder_ == null) {
          upgradeTypeBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              org.bwapi.proxy.messages.GameMessages.UpgradeType, org.bwapi.proxy.messages.GameMessages.UpgradeType.Builder, org.bwapi.proxy.messages.GameMessages.UpgradeTypeOrBuilder>(
                  upgradeType_,
                  getParentForChildren(),
                  isClean());
          upgradeType_ = null;
        }
        return upgradeTypeBuilder_;
      }

      // optional int32 slot = 9;
      private int slot_ ;
      /**
       * <code>optional int32 slot = 9;</code>
       */
      public boolean hasSlot() {
        return ((bitField0_ & 0x00000100) == 0x00000100);
      }
      /**
       * <code>optional int32 slot = 9;</code>
       */
      public int getSlot() {
        return slot_;
      }
      /**
       * <code>optional int32 slot = 9;</code>
       */
      public Builder setSlot(int value) {
        bitField0_ |= 0x00000100;
        slot_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 slot = 9;</code>
       */
      public Builder clearSlot() {
        bitField0_ = (bitField0_ & ~0x00000100);
        slot_ = 0;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:messages.Command)
    }

    static {
      defaultInstance = new Command(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:messages.Command)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_messages_Command_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_messages_Command_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\rcommand.proto\022\010messages\032\nunit.proto\032\013t" +
      "ypes.proto\"\300\002\n\007Command\022#\n\004type\030\001 \002(\0162\025.m" +
      "essages.CommandType\022\036\n\004self\030\002 \002(\0132\020.mess" +
      "ages.UnitId\022\037\n\003pos\030\003 \001(\0132\022.messages.Posi" +
      "tion\022\'\n\007tilePos\030\004 \001(\0132\026.messages.TilePos" +
      "ition\022 \n\006target\030\005 \001(\0132\020.messages.UnitId\022" +
      "$\n\010unitType\030\006 \001(\0132\022.messages.UnitType\022$\n" +
      "\010techType\030\007 \001(\0132\022.messages.TechType\022*\n\013u" +
      "pgradeType\030\010 \001(\0132\025.messages.UpgradeType\022" +
      "\014\n\004slot\030\t \001(\005*\373\004\n\013CommandType\022\010\n\004none\020\001\022",
      "\016\n\nattackMove\020\002\022\016\n\nattackUnit\020\003\022\016\n\nright" +
      "Click\020\004\022\022\n\016rightClickUnit\020\005\022\t\n\005train\020\006\022\t" +
      "\n\005build\020\007\022\016\n\nbuildAddon\020\010\022\014\n\010research\020\t\022" +
      "\013\n\007upgrade\020\n\022\010\n\004stop\020\013\022\020\n\014holdPosition\020\014" +
      "\022\n\n\006patrol\020\r\022\n\n\006follow\020\016\022\024\n\020setRallyPosi" +
      "tion\020\017\022\020\n\014setRallyUnit\020\020\022\n\n\006repair\020\021\022\t\n\005" +
      "morph\020\022\022\n\n\006burrow\020\023\022\014\n\010unburrow\020\024\022\t\n\005sie" +
      "ge\020\025\022\013\n\007unsiege\020\026\022\t\n\005cloak\020\027\022\013\n\007decloak\020" +
      "\030\022\010\n\004lift\020\031\022\010\n\004land\020\032\022\010\n\004load\020\033\022\n\n\006unloa" +
      "d\020\034\022\r\n\tunloadAll\020\035\022\025\n\021unloadAllPosition\020",
      "\036\022\026\n\022cancelConstruction\020\037\022\024\n\020haltConstru" +
      "ction\020 \022\017\n\013cancelMorph\020!\022\017\n\013cancelTrain\020" +
      "\"\022\023\n\017cancelTrainSlot\020#\022\017\n\013cancelAddon\020$\022" +
      "\022\n\016cancelResearch\020%\022\021\n\rcancelUpgrade\020&\022\013" +
      "\n\007useTech\020\'\022\023\n\017useTechPosition\020(\022\021\n\ruseT" +
      "echTarget\020)B$\n\030org.bwapi.proxy.messagesB" +
      "\010Commands"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_messages_Command_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_messages_Command_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_messages_Command_descriptor,
              new java.lang.String[] { "Type", "Self", "Pos", "TilePos", "Target", "UnitType", "TechType", "UpgradeType", "Slot", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          org.bwapi.proxy.messages.GameMessages.getDescriptor(),
          org.bwapi.proxy.messages.BasicTypes.getDescriptor(),
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
