// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: draw.proto

package org.bwapi.proxy.messages;

public final class DrawCommands {
  private DrawCommands() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  /**
   * Protobuf enum {@code messages.ShapeType}
   */
  public enum ShapeType
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>setTextSize = 1;</code>
     */
    setTextSize(0, 1),
    /**
     * <code>text = 2;</code>
     */
    text(1, 2),
    /**
     * <code>box = 3;</code>
     */
    box(2, 3),
    /**
     * <code>circle = 4;</code>
     */
    circle(3, 4),
    /**
     * <code>ellipse = 5;</code>
     */
    ellipse(4, 5),
    /**
     * <code>dot = 6;</code>
     */
    dot(5, 6),
    /**
     * <code>line = 7;</code>
     */
    line(6, 7),
    /**
     * <code>triangle = 8;</code>
     */
    triangle(7, 8),
    ;

    /**
     * <code>setTextSize = 1;</code>
     */
    public static final int setTextSize_VALUE = 1;
    /**
     * <code>text = 2;</code>
     */
    public static final int text_VALUE = 2;
    /**
     * <code>box = 3;</code>
     */
    public static final int box_VALUE = 3;
    /**
     * <code>circle = 4;</code>
     */
    public static final int circle_VALUE = 4;
    /**
     * <code>ellipse = 5;</code>
     */
    public static final int ellipse_VALUE = 5;
    /**
     * <code>dot = 6;</code>
     */
    public static final int dot_VALUE = 6;
    /**
     * <code>line = 7;</code>
     */
    public static final int line_VALUE = 7;
    /**
     * <code>triangle = 8;</code>
     */
    public static final int triangle_VALUE = 8;


    public final int getNumber() { return value; }

    public static ShapeType valueOf(int value) {
      switch (value) {
        case 1: return setTextSize;
        case 2: return text;
        case 3: return box;
        case 4: return circle;
        case 5: return ellipse;
        case 6: return dot;
        case 7: return line;
        case 8: return triangle;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<ShapeType>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static com.google.protobuf.Internal.EnumLiteMap<ShapeType>
        internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<ShapeType>() {
            public ShapeType findValueByNumber(int number) {
              return ShapeType.valueOf(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(index);
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return org.bwapi.proxy.messages.DrawCommands.getDescriptor().getEnumTypes().get(0);
    }

    private static final ShapeType[] VALUES = values();

    public static ShapeType valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      return VALUES[desc.getIndex()];
    }

    private final int index;
    private final int value;

    private ShapeType(int index, int value) {
      this.index = index;
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:messages.ShapeType)
  }

  /**
   * Protobuf enum {@code messages.CoordinateType}
   */
  public enum CoordinateType
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>screen = 1;</code>
     */
    screen(0, 1),
    /**
     * <code>map = 2;</code>
     */
    map(1, 2),
    /**
     * <code>mouse = 3;</code>
     */
    mouse(2, 3),
    ;

    /**
     * <code>screen = 1;</code>
     */
    public static final int screen_VALUE = 1;
    /**
     * <code>map = 2;</code>
     */
    public static final int map_VALUE = 2;
    /**
     * <code>mouse = 3;</code>
     */
    public static final int mouse_VALUE = 3;


    public final int getNumber() { return value; }

    public static CoordinateType valueOf(int value) {
      switch (value) {
        case 1: return screen;
        case 2: return map;
        case 3: return mouse;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<CoordinateType>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static com.google.protobuf.Internal.EnumLiteMap<CoordinateType>
        internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<CoordinateType>() {
            public CoordinateType findValueByNumber(int number) {
              return CoordinateType.valueOf(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(index);
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return org.bwapi.proxy.messages.DrawCommands.getDescriptor().getEnumTypes().get(1);
    }

    private static final CoordinateType[] VALUES = values();

    public static CoordinateType valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      return VALUES[desc.getIndex()];
    }

    private final int index;
    private final int value;

    private CoordinateType(int index, int value) {
      this.index = index;
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:messages.CoordinateType)
  }

  public interface ColorOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // optional int32 id = 1;
    /**
     * <code>optional int32 id = 1;</code>
     */
    boolean hasId();
    /**
     * <code>optional int32 id = 1;</code>
     */
    int getId();

    // optional int32 red = 2;
    /**
     * <code>optional int32 red = 2;</code>
     */
    boolean hasRed();
    /**
     * <code>optional int32 red = 2;</code>
     */
    int getRed();

    // optional int32 green = 3;
    /**
     * <code>optional int32 green = 3;</code>
     */
    boolean hasGreen();
    /**
     * <code>optional int32 green = 3;</code>
     */
    int getGreen();

    // optional int32 blue = 4;
    /**
     * <code>optional int32 blue = 4;</code>
     */
    boolean hasBlue();
    /**
     * <code>optional int32 blue = 4;</code>
     */
    int getBlue();
  }
  /**
   * Protobuf type {@code messages.Color}
   */
  public static final class Color extends
      com.google.protobuf.GeneratedMessage
      implements ColorOrBuilder {
    // Use Color.newBuilder() to construct.
    private Color(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private Color(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final Color defaultInstance;
    public static Color getDefaultInstance() {
      return defaultInstance;
    }

    public Color getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private Color(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              id_ = input.readInt32();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              red_ = input.readInt32();
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              green_ = input.readInt32();
              break;
            }
            case 32: {
              bitField0_ |= 0x00000008;
              blue_ = input.readInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.bwapi.proxy.messages.DrawCommands.internal_static_messages_Color_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.bwapi.proxy.messages.DrawCommands.internal_static_messages_Color_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.bwapi.proxy.messages.DrawCommands.Color.class, org.bwapi.proxy.messages.DrawCommands.Color.Builder.class);
    }

    public static com.google.protobuf.Parser<Color> PARSER =
        new com.google.protobuf.AbstractParser<Color>() {
      public Color parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Color(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<Color> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // optional int32 id = 1;
    public static final int ID_FIELD_NUMBER = 1;
    private int id_;
    /**
     * <code>optional int32 id = 1;</code>
     */
    public boolean hasId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional int32 id = 1;</code>
     */
    public int getId() {
      return id_;
    }

    // optional int32 red = 2;
    public static final int RED_FIELD_NUMBER = 2;
    private int red_;
    /**
     * <code>optional int32 red = 2;</code>
     */
    public boolean hasRed() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional int32 red = 2;</code>
     */
    public int getRed() {
      return red_;
    }

    // optional int32 green = 3;
    public static final int GREEN_FIELD_NUMBER = 3;
    private int green_;
    /**
     * <code>optional int32 green = 3;</code>
     */
    public boolean hasGreen() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional int32 green = 3;</code>
     */
    public int getGreen() {
      return green_;
    }

    // optional int32 blue = 4;
    public static final int BLUE_FIELD_NUMBER = 4;
    private int blue_;
    /**
     * <code>optional int32 blue = 4;</code>
     */
    public boolean hasBlue() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>optional int32 blue = 4;</code>
     */
    public int getBlue() {
      return blue_;
    }

    private void initFields() {
      id_ = 0;
      red_ = 0;
      green_ = 0;
      blue_ = 0;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, id_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt32(2, red_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeInt32(3, green_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeInt32(4, blue_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, id_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, red_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, green_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(4, blue_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static org.bwapi.proxy.messages.DrawCommands.Color parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.bwapi.proxy.messages.DrawCommands.Color parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.bwapi.proxy.messages.DrawCommands.Color parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.bwapi.proxy.messages.DrawCommands.Color parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.bwapi.proxy.messages.DrawCommands.Color parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static org.bwapi.proxy.messages.DrawCommands.Color parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static org.bwapi.proxy.messages.DrawCommands.Color parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static org.bwapi.proxy.messages.DrawCommands.Color parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static org.bwapi.proxy.messages.DrawCommands.Color parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static org.bwapi.proxy.messages.DrawCommands.Color parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(org.bwapi.proxy.messages.DrawCommands.Color prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code messages.Color}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements org.bwapi.proxy.messages.DrawCommands.ColorOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.bwapi.proxy.messages.DrawCommands.internal_static_messages_Color_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.bwapi.proxy.messages.DrawCommands.internal_static_messages_Color_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                org.bwapi.proxy.messages.DrawCommands.Color.class, org.bwapi.proxy.messages.DrawCommands.Color.Builder.class);
      }

      // Construct using org.bwapi.proxy.messages.DrawCommands.Color.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        id_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        red_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        green_ = 0;
        bitField0_ = (bitField0_ & ~0x00000004);
        blue_ = 0;
        bitField0_ = (bitField0_ & ~0x00000008);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.bwapi.proxy.messages.DrawCommands.internal_static_messages_Color_descriptor;
      }

      public org.bwapi.proxy.messages.DrawCommands.Color getDefaultInstanceForType() {
        return org.bwapi.proxy.messages.DrawCommands.Color.getDefaultInstance();
      }

      public org.bwapi.proxy.messages.DrawCommands.Color build() {
        org.bwapi.proxy.messages.DrawCommands.Color result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public org.bwapi.proxy.messages.DrawCommands.Color buildPartial() {
        org.bwapi.proxy.messages.DrawCommands.Color result = new org.bwapi.proxy.messages.DrawCommands.Color(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.id_ = id_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.red_ = red_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.green_ = green_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.blue_ = blue_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.bwapi.proxy.messages.DrawCommands.Color) {
          return mergeFrom((org.bwapi.proxy.messages.DrawCommands.Color)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(org.bwapi.proxy.messages.DrawCommands.Color other) {
        if (other == org.bwapi.proxy.messages.DrawCommands.Color.getDefaultInstance()) return this;
        if (other.hasId()) {
          setId(other.getId());
        }
        if (other.hasRed()) {
          setRed(other.getRed());
        }
        if (other.hasGreen()) {
          setGreen(other.getGreen());
        }
        if (other.hasBlue()) {
          setBlue(other.getBlue());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        org.bwapi.proxy.messages.DrawCommands.Color parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (org.bwapi.proxy.messages.DrawCommands.Color) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // optional int32 id = 1;
      private int id_ ;
      /**
       * <code>optional int32 id = 1;</code>
       */
      public boolean hasId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional int32 id = 1;</code>
       */
      public int getId() {
        return id_;
      }
      /**
       * <code>optional int32 id = 1;</code>
       */
      public Builder setId(int value) {
        bitField0_ |= 0x00000001;
        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 id = 1;</code>
       */
      public Builder clearId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        id_ = 0;
        onChanged();
        return this;
      }

      // optional int32 red = 2;
      private int red_ ;
      /**
       * <code>optional int32 red = 2;</code>
       */
      public boolean hasRed() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional int32 red = 2;</code>
       */
      public int getRed() {
        return red_;
      }
      /**
       * <code>optional int32 red = 2;</code>
       */
      public Builder setRed(int value) {
        bitField0_ |= 0x00000002;
        red_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 red = 2;</code>
       */
      public Builder clearRed() {
        bitField0_ = (bitField0_ & ~0x00000002);
        red_ = 0;
        onChanged();
        return this;
      }

      // optional int32 green = 3;
      private int green_ ;
      /**
       * <code>optional int32 green = 3;</code>
       */
      public boolean hasGreen() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional int32 green = 3;</code>
       */
      public int getGreen() {
        return green_;
      }
      /**
       * <code>optional int32 green = 3;</code>
       */
      public Builder setGreen(int value) {
        bitField0_ |= 0x00000004;
        green_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 green = 3;</code>
       */
      public Builder clearGreen() {
        bitField0_ = (bitField0_ & ~0x00000004);
        green_ = 0;
        onChanged();
        return this;
      }

      // optional int32 blue = 4;
      private int blue_ ;
      /**
       * <code>optional int32 blue = 4;</code>
       */
      public boolean hasBlue() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>optional int32 blue = 4;</code>
       */
      public int getBlue() {
        return blue_;
      }
      /**
       * <code>optional int32 blue = 4;</code>
       */
      public Builder setBlue(int value) {
        bitField0_ |= 0x00000008;
        blue_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 blue = 4;</code>
       */
      public Builder clearBlue() {
        bitField0_ = (bitField0_ & ~0x00000008);
        blue_ = 0;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:messages.Color)
    }

    static {
      defaultInstance = new Color(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:messages.Color)
  }

  public interface DrawCommandOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required .messages.ShapeType shape = 1;
    /**
     * <code>required .messages.ShapeType shape = 1;</code>
     */
    boolean hasShape();
    /**
     * <code>required .messages.ShapeType shape = 1;</code>
     */
    org.bwapi.proxy.messages.DrawCommands.ShapeType getShape();

    // optional .messages.CoordinateType coordinateType = 2;
    /**
     * <code>optional .messages.CoordinateType coordinateType = 2;</code>
     */
    boolean hasCoordinateType();
    /**
     * <code>optional .messages.CoordinateType coordinateType = 2;</code>
     */
    org.bwapi.proxy.messages.DrawCommands.CoordinateType getCoordinateType();

    // repeated int32 coordinates = 3;
    /**
     * <code>repeated int32 coordinates = 3;</code>
     */
    java.util.List<java.lang.Integer> getCoordinatesList();
    /**
     * <code>repeated int32 coordinates = 3;</code>
     */
    int getCoordinatesCount();
    /**
     * <code>repeated int32 coordinates = 3;</code>
     */
    int getCoordinates(int index);

    // optional .messages.Color color = 4;
    /**
     * <code>optional .messages.Color color = 4;</code>
     */
    boolean hasColor();
    /**
     * <code>optional .messages.Color color = 4;</code>
     */
    org.bwapi.proxy.messages.DrawCommands.Color getColor();
    /**
     * <code>optional .messages.Color color = 4;</code>
     */
    org.bwapi.proxy.messages.DrawCommands.ColorOrBuilder getColorOrBuilder();

    // optional bool isSolid = 5;
    /**
     * <code>optional bool isSolid = 5;</code>
     */
    boolean hasIsSolid();
    /**
     * <code>optional bool isSolid = 5;</code>
     */
    boolean getIsSolid();

    // optional string text = 6;
    /**
     * <code>optional string text = 6;</code>
     */
    boolean hasText();
    /**
     * <code>optional string text = 6;</code>
     */
    java.lang.String getText();
    /**
     * <code>optional string text = 6;</code>
     */
    com.google.protobuf.ByteString
        getTextBytes();
  }
  /**
   * Protobuf type {@code messages.DrawCommand}
   */
  public static final class DrawCommand extends
      com.google.protobuf.GeneratedMessage
      implements DrawCommandOrBuilder {
    // Use DrawCommand.newBuilder() to construct.
    private DrawCommand(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private DrawCommand(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final DrawCommand defaultInstance;
    public static DrawCommand getDefaultInstance() {
      return defaultInstance;
    }

    public DrawCommand getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private DrawCommand(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              int rawValue = input.readEnum();
              org.bwapi.proxy.messages.DrawCommands.ShapeType value = org.bwapi.proxy.messages.DrawCommands.ShapeType.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(1, rawValue);
              } else {
                bitField0_ |= 0x00000001;
                shape_ = value;
              }
              break;
            }
            case 16: {
              int rawValue = input.readEnum();
              org.bwapi.proxy.messages.DrawCommands.CoordinateType value = org.bwapi.proxy.messages.DrawCommands.CoordinateType.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(2, rawValue);
              } else {
                bitField0_ |= 0x00000002;
                coordinateType_ = value;
              }
              break;
            }
            case 24: {
              if (!((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
                coordinates_ = new java.util.ArrayList<java.lang.Integer>();
                mutable_bitField0_ |= 0x00000004;
              }
              coordinates_.add(input.readInt32());
              break;
            }
            case 26: {
              int length = input.readRawVarint32();
              int limit = input.pushLimit(length);
              if (!((mutable_bitField0_ & 0x00000004) == 0x00000004) && input.getBytesUntilLimit() > 0) {
                coordinates_ = new java.util.ArrayList<java.lang.Integer>();
                mutable_bitField0_ |= 0x00000004;
              }
              while (input.getBytesUntilLimit() > 0) {
                coordinates_.add(input.readInt32());
              }
              input.popLimit(limit);
              break;
            }
            case 34: {
              org.bwapi.proxy.messages.DrawCommands.Color.Builder subBuilder = null;
              if (((bitField0_ & 0x00000004) == 0x00000004)) {
                subBuilder = color_.toBuilder();
              }
              color_ = input.readMessage(org.bwapi.proxy.messages.DrawCommands.Color.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(color_);
                color_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000004;
              break;
            }
            case 40: {
              bitField0_ |= 0x00000008;
              isSolid_ = input.readBool();
              break;
            }
            case 50: {
              bitField0_ |= 0x00000010;
              text_ = input.readBytes();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
          coordinates_ = java.util.Collections.unmodifiableList(coordinates_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.bwapi.proxy.messages.DrawCommands.internal_static_messages_DrawCommand_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.bwapi.proxy.messages.DrawCommands.internal_static_messages_DrawCommand_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.bwapi.proxy.messages.DrawCommands.DrawCommand.class, org.bwapi.proxy.messages.DrawCommands.DrawCommand.Builder.class);
    }

    public static com.google.protobuf.Parser<DrawCommand> PARSER =
        new com.google.protobuf.AbstractParser<DrawCommand>() {
      public DrawCommand parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new DrawCommand(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<DrawCommand> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // required .messages.ShapeType shape = 1;
    public static final int SHAPE_FIELD_NUMBER = 1;
    private org.bwapi.proxy.messages.DrawCommands.ShapeType shape_;
    /**
     * <code>required .messages.ShapeType shape = 1;</code>
     */
    public boolean hasShape() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required .messages.ShapeType shape = 1;</code>
     */
    public org.bwapi.proxy.messages.DrawCommands.ShapeType getShape() {
      return shape_;
    }

    // optional .messages.CoordinateType coordinateType = 2;
    public static final int COORDINATETYPE_FIELD_NUMBER = 2;
    private org.bwapi.proxy.messages.DrawCommands.CoordinateType coordinateType_;
    /**
     * <code>optional .messages.CoordinateType coordinateType = 2;</code>
     */
    public boolean hasCoordinateType() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional .messages.CoordinateType coordinateType = 2;</code>
     */
    public org.bwapi.proxy.messages.DrawCommands.CoordinateType getCoordinateType() {
      return coordinateType_;
    }

    // repeated int32 coordinates = 3;
    public static final int COORDINATES_FIELD_NUMBER = 3;
    private java.util.List<java.lang.Integer> coordinates_;
    /**
     * <code>repeated int32 coordinates = 3;</code>
     */
    public java.util.List<java.lang.Integer>
        getCoordinatesList() {
      return coordinates_;
    }
    /**
     * <code>repeated int32 coordinates = 3;</code>
     */
    public int getCoordinatesCount() {
      return coordinates_.size();
    }
    /**
     * <code>repeated int32 coordinates = 3;</code>
     */
    public int getCoordinates(int index) {
      return coordinates_.get(index);
    }

    // optional .messages.Color color = 4;
    public static final int COLOR_FIELD_NUMBER = 4;
    private org.bwapi.proxy.messages.DrawCommands.Color color_;
    /**
     * <code>optional .messages.Color color = 4;</code>
     */
    public boolean hasColor() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional .messages.Color color = 4;</code>
     */
    public org.bwapi.proxy.messages.DrawCommands.Color getColor() {
      return color_;
    }
    /**
     * <code>optional .messages.Color color = 4;</code>
     */
    public org.bwapi.proxy.messages.DrawCommands.ColorOrBuilder getColorOrBuilder() {
      return color_;
    }

    // optional bool isSolid = 5;
    public static final int ISSOLID_FIELD_NUMBER = 5;
    private boolean isSolid_;
    /**
     * <code>optional bool isSolid = 5;</code>
     */
    public boolean hasIsSolid() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>optional bool isSolid = 5;</code>
     */
    public boolean getIsSolid() {
      return isSolid_;
    }

    // optional string text = 6;
    public static final int TEXT_FIELD_NUMBER = 6;
    private java.lang.Object text_;
    /**
     * <code>optional string text = 6;</code>
     */
    public boolean hasText() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    /**
     * <code>optional string text = 6;</code>
     */
    public java.lang.String getText() {
      java.lang.Object ref = text_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          text_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string text = 6;</code>
     */
    public com.google.protobuf.ByteString
        getTextBytes() {
      java.lang.Object ref = text_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        text_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private void initFields() {
      shape_ = org.bwapi.proxy.messages.DrawCommands.ShapeType.setTextSize;
      coordinateType_ = org.bwapi.proxy.messages.DrawCommands.CoordinateType.screen;
      coordinates_ = java.util.Collections.emptyList();
      color_ = org.bwapi.proxy.messages.DrawCommands.Color.getDefaultInstance();
      isSolid_ = false;
      text_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasShape()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeEnum(1, shape_.getNumber());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeEnum(2, coordinateType_.getNumber());
      }
      for (int i = 0; i < coordinates_.size(); i++) {
        output.writeInt32(3, coordinates_.get(i));
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeMessage(4, color_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeBool(5, isSolid_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeBytes(6, getTextBytes());
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, shape_.getNumber());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(2, coordinateType_.getNumber());
      }
      {
        int dataSize = 0;
        for (int i = 0; i < coordinates_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeInt32SizeNoTag(coordinates_.get(i));
        }
        size += dataSize;
        size += 1 * getCoordinatesList().size();
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(4, color_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(5, isSolid_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(6, getTextBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static org.bwapi.proxy.messages.DrawCommands.DrawCommand parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.bwapi.proxy.messages.DrawCommands.DrawCommand parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.bwapi.proxy.messages.DrawCommands.DrawCommand parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.bwapi.proxy.messages.DrawCommands.DrawCommand parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.bwapi.proxy.messages.DrawCommands.DrawCommand parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static org.bwapi.proxy.messages.DrawCommands.DrawCommand parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static org.bwapi.proxy.messages.DrawCommands.DrawCommand parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static org.bwapi.proxy.messages.DrawCommands.DrawCommand parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static org.bwapi.proxy.messages.DrawCommands.DrawCommand parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static org.bwapi.proxy.messages.DrawCommands.DrawCommand parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(org.bwapi.proxy.messages.DrawCommands.DrawCommand prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code messages.DrawCommand}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements org.bwapi.proxy.messages.DrawCommands.DrawCommandOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.bwapi.proxy.messages.DrawCommands.internal_static_messages_DrawCommand_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.bwapi.proxy.messages.DrawCommands.internal_static_messages_DrawCommand_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                org.bwapi.proxy.messages.DrawCommands.DrawCommand.class, org.bwapi.proxy.messages.DrawCommands.DrawCommand.Builder.class);
      }

      // Construct using org.bwapi.proxy.messages.DrawCommands.DrawCommand.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getColorFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        shape_ = org.bwapi.proxy.messages.DrawCommands.ShapeType.setTextSize;
        bitField0_ = (bitField0_ & ~0x00000001);
        coordinateType_ = org.bwapi.proxy.messages.DrawCommands.CoordinateType.screen;
        bitField0_ = (bitField0_ & ~0x00000002);
        coordinates_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000004);
        if (colorBuilder_ == null) {
          color_ = org.bwapi.proxy.messages.DrawCommands.Color.getDefaultInstance();
        } else {
          colorBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000008);
        isSolid_ = false;
        bitField0_ = (bitField0_ & ~0x00000010);
        text_ = "";
        bitField0_ = (bitField0_ & ~0x00000020);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.bwapi.proxy.messages.DrawCommands.internal_static_messages_DrawCommand_descriptor;
      }

      public org.bwapi.proxy.messages.DrawCommands.DrawCommand getDefaultInstanceForType() {
        return org.bwapi.proxy.messages.DrawCommands.DrawCommand.getDefaultInstance();
      }

      public org.bwapi.proxy.messages.DrawCommands.DrawCommand build() {
        org.bwapi.proxy.messages.DrawCommands.DrawCommand result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public org.bwapi.proxy.messages.DrawCommands.DrawCommand buildPartial() {
        org.bwapi.proxy.messages.DrawCommands.DrawCommand result = new org.bwapi.proxy.messages.DrawCommands.DrawCommand(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.shape_ = shape_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.coordinateType_ = coordinateType_;
        if (((bitField0_ & 0x00000004) == 0x00000004)) {
          coordinates_ = java.util.Collections.unmodifiableList(coordinates_);
          bitField0_ = (bitField0_ & ~0x00000004);
        }
        result.coordinates_ = coordinates_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000004;
        }
        if (colorBuilder_ == null) {
          result.color_ = color_;
        } else {
          result.color_ = colorBuilder_.build();
        }
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000008;
        }
        result.isSolid_ = isSolid_;
        if (((from_bitField0_ & 0x00000020) == 0x00000020)) {
          to_bitField0_ |= 0x00000010;
        }
        result.text_ = text_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.bwapi.proxy.messages.DrawCommands.DrawCommand) {
          return mergeFrom((org.bwapi.proxy.messages.DrawCommands.DrawCommand)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(org.bwapi.proxy.messages.DrawCommands.DrawCommand other) {
        if (other == org.bwapi.proxy.messages.DrawCommands.DrawCommand.getDefaultInstance()) return this;
        if (other.hasShape()) {
          setShape(other.getShape());
        }
        if (other.hasCoordinateType()) {
          setCoordinateType(other.getCoordinateType());
        }
        if (!other.coordinates_.isEmpty()) {
          if (coordinates_.isEmpty()) {
            coordinates_ = other.coordinates_;
            bitField0_ = (bitField0_ & ~0x00000004);
          } else {
            ensureCoordinatesIsMutable();
            coordinates_.addAll(other.coordinates_);
          }
          onChanged();
        }
        if (other.hasColor()) {
          mergeColor(other.getColor());
        }
        if (other.hasIsSolid()) {
          setIsSolid(other.getIsSolid());
        }
        if (other.hasText()) {
          bitField0_ |= 0x00000020;
          text_ = other.text_;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasShape()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        org.bwapi.proxy.messages.DrawCommands.DrawCommand parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (org.bwapi.proxy.messages.DrawCommands.DrawCommand) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required .messages.ShapeType shape = 1;
      private org.bwapi.proxy.messages.DrawCommands.ShapeType shape_ = org.bwapi.proxy.messages.DrawCommands.ShapeType.setTextSize;
      /**
       * <code>required .messages.ShapeType shape = 1;</code>
       */
      public boolean hasShape() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required .messages.ShapeType shape = 1;</code>
       */
      public org.bwapi.proxy.messages.DrawCommands.ShapeType getShape() {
        return shape_;
      }
      /**
       * <code>required .messages.ShapeType shape = 1;</code>
       */
      public Builder setShape(org.bwapi.proxy.messages.DrawCommands.ShapeType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000001;
        shape_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required .messages.ShapeType shape = 1;</code>
       */
      public Builder clearShape() {
        bitField0_ = (bitField0_ & ~0x00000001);
        shape_ = org.bwapi.proxy.messages.DrawCommands.ShapeType.setTextSize;
        onChanged();
        return this;
      }

      // optional .messages.CoordinateType coordinateType = 2;
      private org.bwapi.proxy.messages.DrawCommands.CoordinateType coordinateType_ = org.bwapi.proxy.messages.DrawCommands.CoordinateType.screen;
      /**
       * <code>optional .messages.CoordinateType coordinateType = 2;</code>
       */
      public boolean hasCoordinateType() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional .messages.CoordinateType coordinateType = 2;</code>
       */
      public org.bwapi.proxy.messages.DrawCommands.CoordinateType getCoordinateType() {
        return coordinateType_;
      }
      /**
       * <code>optional .messages.CoordinateType coordinateType = 2;</code>
       */
      public Builder setCoordinateType(org.bwapi.proxy.messages.DrawCommands.CoordinateType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000002;
        coordinateType_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional .messages.CoordinateType coordinateType = 2;</code>
       */
      public Builder clearCoordinateType() {
        bitField0_ = (bitField0_ & ~0x00000002);
        coordinateType_ = org.bwapi.proxy.messages.DrawCommands.CoordinateType.screen;
        onChanged();
        return this;
      }

      // repeated int32 coordinates = 3;
      private java.util.List<java.lang.Integer> coordinates_ = java.util.Collections.emptyList();
      private void ensureCoordinatesIsMutable() {
        if (!((bitField0_ & 0x00000004) == 0x00000004)) {
          coordinates_ = new java.util.ArrayList<java.lang.Integer>(coordinates_);
          bitField0_ |= 0x00000004;
         }
      }
      /**
       * <code>repeated int32 coordinates = 3;</code>
       */
      public java.util.List<java.lang.Integer>
          getCoordinatesList() {
        return java.util.Collections.unmodifiableList(coordinates_);
      }
      /**
       * <code>repeated int32 coordinates = 3;</code>
       */
      public int getCoordinatesCount() {
        return coordinates_.size();
      }
      /**
       * <code>repeated int32 coordinates = 3;</code>
       */
      public int getCoordinates(int index) {
        return coordinates_.get(index);
      }
      /**
       * <code>repeated int32 coordinates = 3;</code>
       */
      public Builder setCoordinates(
          int index, int value) {
        ensureCoordinatesIsMutable();
        coordinates_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated int32 coordinates = 3;</code>
       */
      public Builder addCoordinates(int value) {
        ensureCoordinatesIsMutable();
        coordinates_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated int32 coordinates = 3;</code>
       */
      public Builder addAllCoordinates(
          java.lang.Iterable<? extends java.lang.Integer> values) {
        ensureCoordinatesIsMutable();
        super.addAll(values, coordinates_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated int32 coordinates = 3;</code>
       */
      public Builder clearCoordinates() {
        coordinates_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000004);
        onChanged();
        return this;
      }

      // optional .messages.Color color = 4;
      private org.bwapi.proxy.messages.DrawCommands.Color color_ = org.bwapi.proxy.messages.DrawCommands.Color.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          org.bwapi.proxy.messages.DrawCommands.Color, org.bwapi.proxy.messages.DrawCommands.Color.Builder, org.bwapi.proxy.messages.DrawCommands.ColorOrBuilder> colorBuilder_;
      /**
       * <code>optional .messages.Color color = 4;</code>
       */
      public boolean hasColor() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>optional .messages.Color color = 4;</code>
       */
      public org.bwapi.proxy.messages.DrawCommands.Color getColor() {
        if (colorBuilder_ == null) {
          return color_;
        } else {
          return colorBuilder_.getMessage();
        }
      }
      /**
       * <code>optional .messages.Color color = 4;</code>
       */
      public Builder setColor(org.bwapi.proxy.messages.DrawCommands.Color value) {
        if (colorBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          color_ = value;
          onChanged();
        } else {
          colorBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000008;
        return this;
      }
      /**
       * <code>optional .messages.Color color = 4;</code>
       */
      public Builder setColor(
          org.bwapi.proxy.messages.DrawCommands.Color.Builder builderForValue) {
        if (colorBuilder_ == null) {
          color_ = builderForValue.build();
          onChanged();
        } else {
          colorBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000008;
        return this;
      }
      /**
       * <code>optional .messages.Color color = 4;</code>
       */
      public Builder mergeColor(org.bwapi.proxy.messages.DrawCommands.Color value) {
        if (colorBuilder_ == null) {
          if (((bitField0_ & 0x00000008) == 0x00000008) &&
              color_ != org.bwapi.proxy.messages.DrawCommands.Color.getDefaultInstance()) {
            color_ =
              org.bwapi.proxy.messages.DrawCommands.Color.newBuilder(color_).mergeFrom(value).buildPartial();
          } else {
            color_ = value;
          }
          onChanged();
        } else {
          colorBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000008;
        return this;
      }
      /**
       * <code>optional .messages.Color color = 4;</code>
       */
      public Builder clearColor() {
        if (colorBuilder_ == null) {
          color_ = org.bwapi.proxy.messages.DrawCommands.Color.getDefaultInstance();
          onChanged();
        } else {
          colorBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000008);
        return this;
      }
      /**
       * <code>optional .messages.Color color = 4;</code>
       */
      public org.bwapi.proxy.messages.DrawCommands.Color.Builder getColorBuilder() {
        bitField0_ |= 0x00000008;
        onChanged();
        return getColorFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .messages.Color color = 4;</code>
       */
      public org.bwapi.proxy.messages.DrawCommands.ColorOrBuilder getColorOrBuilder() {
        if (colorBuilder_ != null) {
          return colorBuilder_.getMessageOrBuilder();
        } else {
          return color_;
        }
      }
      /**
       * <code>optional .messages.Color color = 4;</code>
       */
      private com.google.protobuf.SingleFieldBuilder<
          org.bwapi.proxy.messages.DrawCommands.Color, org.bwapi.proxy.messages.DrawCommands.Color.Builder, org.bwapi.proxy.messages.DrawCommands.ColorOrBuilder> 
          getColorFieldBuilder() {
        if (colorBuilder_ == null) {
          colorBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              org.bwapi.proxy.messages.DrawCommands.Color, org.bwapi.proxy.messages.DrawCommands.Color.Builder, org.bwapi.proxy.messages.DrawCommands.ColorOrBuilder>(
                  color_,
                  getParentForChildren(),
                  isClean());
          color_ = null;
        }
        return colorBuilder_;
      }

      // optional bool isSolid = 5;
      private boolean isSolid_ ;
      /**
       * <code>optional bool isSolid = 5;</code>
       */
      public boolean hasIsSolid() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      /**
       * <code>optional bool isSolid = 5;</code>
       */
      public boolean getIsSolid() {
        return isSolid_;
      }
      /**
       * <code>optional bool isSolid = 5;</code>
       */
      public Builder setIsSolid(boolean value) {
        bitField0_ |= 0x00000010;
        isSolid_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bool isSolid = 5;</code>
       */
      public Builder clearIsSolid() {
        bitField0_ = (bitField0_ & ~0x00000010);
        isSolid_ = false;
        onChanged();
        return this;
      }

      // optional string text = 6;
      private java.lang.Object text_ = "";
      /**
       * <code>optional string text = 6;</code>
       */
      public boolean hasText() {
        return ((bitField0_ & 0x00000020) == 0x00000020);
      }
      /**
       * <code>optional string text = 6;</code>
       */
      public java.lang.String getText() {
        java.lang.Object ref = text_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          text_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string text = 6;</code>
       */
      public com.google.protobuf.ByteString
          getTextBytes() {
        java.lang.Object ref = text_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          text_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string text = 6;</code>
       */
      public Builder setText(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000020;
        text_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string text = 6;</code>
       */
      public Builder clearText() {
        bitField0_ = (bitField0_ & ~0x00000020);
        text_ = getDefaultInstance().getText();
        onChanged();
        return this;
      }
      /**
       * <code>optional string text = 6;</code>
       */
      public Builder setTextBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000020;
        text_ = value;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:messages.DrawCommand)
    }

    static {
      defaultInstance = new DrawCommand(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:messages.DrawCommand)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_messages_Color_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_messages_Color_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_messages_DrawCommand_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_messages_DrawCommand_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\ndraw.proto\022\010messages\"=\n\005Color\022\n\n\002id\030\001 " +
      "\001(\005\022\013\n\003red\030\002 \001(\005\022\r\n\005green\030\003 \001(\005\022\014\n\004blue\030" +
      "\004 \001(\005\"\267\001\n\013DrawCommand\022\"\n\005shape\030\001 \002(\0162\023.m" +
      "essages.ShapeType\0220\n\016coordinateType\030\002 \001(" +
      "\0162\030.messages.CoordinateType\022\023\n\013coordinat" +
      "es\030\003 \003(\005\022\036\n\005color\030\004 \001(\0132\017.messages.Color" +
      "\022\017\n\007isSolid\030\005 \001(\010\022\014\n\004text\030\006 \001(\t*i\n\tShape" +
      "Type\022\017\n\013setTextSize\020\001\022\010\n\004text\020\002\022\007\n\003box\020\003" +
      "\022\n\n\006circle\020\004\022\013\n\007ellipse\020\005\022\007\n\003dot\020\006\022\010\n\004li" +
      "ne\020\007\022\014\n\010triangle\020\010*0\n\016CoordinateType\022\n\n\006",
      "screen\020\001\022\007\n\003map\020\002\022\t\n\005mouse\020\003B(\n\030org.bwap" +
      "i.proxy.messagesB\014DrawCommands"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_messages_Color_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_messages_Color_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_messages_Color_descriptor,
              new java.lang.String[] { "Id", "Red", "Green", "Blue", });
          internal_static_messages_DrawCommand_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_messages_DrawCommand_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_messages_DrawCommand_descriptor,
              new java.lang.String[] { "Shape", "CoordinateType", "Coordinates", "Color", "IsSolid", "Text", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
